[package]
name = "rsiot-logging"
version = "0.0.0"
edition = "2021"
categories.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
tracing = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-loki = { workspace = true }
