[package]
name = "material_components-ui"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "*" }
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.0-rc1", features = ["csr"] }
leptos_router = { version = "0.7.0-rc1" }
rsiot = { path = "../../.", features = [
    "single-thread",
    "logging",
    "cmp_leptos",
    "cmp_plc",
    "cmp_webstorage",
] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "*" }
tracing = "*"
any_spawner = "*"

[workspace]
# members = ["src-tauri"]
