[package]
description = "Типы данных для создания компонентов"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsiot-component-core"
readme = "README.md"
rust-version.workspace = true
version = "0.0.8"

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

rsiot-messages-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
