[package]
name = "rsiot-component-core"
version = "0.0.5"
description = "Типы данных для создания компонентов"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
futures = { workspace = true }
tokio = { workspace = true }

rsiot-messages-core = { workspace = true }
