[package]
name = "rsiot-timescaledb-storing"
version = "0.0.4"
edition = "2021"
description = "Сохранение данных в TimescaleDB"
license = "MIT"

[dependencies]
chrono = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
chrono = { workspace = true }
tracing-subscriber = { workspace = true }
