[package]
name = "rsiot-timescaledb-storing"
version = "0.0.2"
edition = "2021"


[dependencies]
chrono = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
chrono = { workspace = true }
tracing-subscriber = { workspace = true }
