version: "3.8"
name: rsiot-timescaledb-dev

services:
  db:
    container_name: rsiot-timescaledb-dev
    hostname: rsiot-timescaledb-dev
    command: postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: timescale/timescaledb:2.12.2-pg15
    ports:
      - "5432:5432"
    volumes:
      - ../rsiot-timescaledb-config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../rsiot-timescaledb-config/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ../rsiot-timescaledb-config/init.sql:/docker-entrypoint-initdb.d/init.sql
