vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 1
  }
}

style {
    stroke-width: 1
    stroke: gray
}

MsgBusIn: MsgBus {
    shape: oval
}

Input

Buffer {
    style.stroke-dash: 5
}

Periodic

Target: "" {
    SendToCan

    CAN {
        style.stroke-dash: 5
    }

    RcvFromCan

    SendToCan -> CAN

    CAN -> RcvFromCan
}

Output

MsgBusOut: MsgBus {
    shape: oval
}

MsgBusIn -> Input

Input -> Target.SendToCan: mpsc::<CanFrame>
Input -> Buffer

Periodic -> Target.SendToCan: mpsc::<CanFrame>
Periodic <- Buffer


Target.RcvFromCan -> Output: mpsc::<CanFrame>

Output -> MsgBusOut
