[workspace]
members = [
    "./drivers/modbus-client",
    "./drivers/modbus-client-config",
    "./libraries/async-task-utils",
    "./libraries/messages-lib",
    "./modbus-test",
    "./utils/messages",
]
resolver = "2"


[workspace.dependencies]
tokio-modbus = { version = "0.9", default-features = false, features = ["tcp"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
tracing = { version = "0.1" }
url = { version = "2.4" }

async-task-utils = { path = "./libraries/async-task-utils" }
messages = { path = "./utils/messages" }
messages-lib = { path = "./libraries/messages-lib" }
modbus-client = { path = "./drivers/modbus-client" }
modbus-client-config = { path = "./drivers/modbus-client-config" }
