[workspace]
members = [
    "./rsiot",
    "./rsiot-component-core",
    "./rsiot-components-config",
    "./rsiot-env-vars",
    "./rsiot-extra-components",
    "./rsiot-http-client",
    "./rsiot-http-client-wasm",
    "./rsiot-http-server",
    "./rsiot-leptos",
    "./rsiot-logging",
    "./rsiot-macros",
    "./rsiot-messages-core",
    "./rsiot-modbus-client",
    "./rsiot-plc",
    "./rsiot-redis-client",
    "./rsiot-timescaledb-storing",
    "./rsiot-websocket-client",
    "./rsiot-websocket-client-wasm",
    "./rsiot-websocket-server",
]
exclude = ["./rsiot-esp"]
resolver = "2"


[workspace.package]
categories = ["api-bindings", "gui", "network-programming"]
edition = "2021"
keywords = ["iot"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Konstantin-Dudersky/rsiot"
rust-version = "1.75.0"


[workspace.dependencies]

# async
async-trait = { version = "0.1.77" }
futures = { version = "0.3.29" }
futures-util = { version = "0.3.29" }
tokio = { version = "1.35.1", features = ["macros", "sync", "rt", "time"] }
tokio-util = { version = "0.7.10" }

# CLI
clap = { version = "4.4", features = ["derive"] }

# datatypes
chrono = { version = "0.4.31", features = ["serde"] }
http = { version = "1.0.0" }
url = { version = "2.5.0" }
uuid = { version = "1.6.1", features = ["serde", "v4"] }

# documentation
document-features = { version = "0.2.7" }

# database
redis = { version = "0.24.0", features = ["tokio-comp"] }
sqlx = { version = "0.7.3", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
] }

# env vars
dotenvy = { version = "0.15" }
envy = { version = "0.4" }

# errors
anyhow = { version = "1.0.79" }
thiserror = { version = "1.0.56" }

# HTTP-client
reqwest = { version = "0.11.22", features = ["json"] }

# HTTP-server
axum = { version = "0.7.2" }
axum-test = { version = "14.0.0" }
tower-http = { version = "0.5.0", features = ["cors", "trace"] }

# Leptos
leptos = { version = "0.6.0-rc1", features = ["csr"] }
leptos_router = { version = "0.6.0-rc1", features = ["csr"] }

# logging
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tracing-loki = { version = "0.2.4" }
tracing-web = { version = "0.1.3" }

# macro
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = "2.0"

# Modbus
tokio-modbus = { version = "0.10.0", default-features = false, features = [
    "tcp",
] }

# serialization / deserialization
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108" }
toml = { version = "0.8" }

# WASM
gloo = { version = "0.11.0", features = ["net", "futures", "timers", "utils"] }

# Websocket
tokio-tungstenite = { version = "0.21.0" }


# workspace packages
rsiot-component-core = { version = "0.0.40", path = "./rsiot-component-core" }
rsiot-components-config = { version = "0.0.40", path = "./rsiot-components-config" }
rsiot-env-vars = { version = "0.0.40", path = "./rsiot-env-vars" }
rsiot-extra-components = { version = "0.0.40", path = "./rsiot-extra-components" }
rsiot-http-client = { version = "0.0.40", path = "./rsiot-http-client" }
rsiot-http-client-wasm = { version = "0.0.40", path = "./rsiot-http-client-wasm" }
rsiot-http-server = { version = "0.0.40", path = "./rsiot-http-server" }
rsiot-leptos = { version = "0.0.0", path = "./rsiot-leptos" }
rsiot-logging = { version = "0.0.40", path = "./rsiot-logging" }
rsiot-macros = { version = "0.0.40", path = "./rsiot-macros" }
rsiot-messages-core = { version = "0.0.40", path = "./rsiot-messages-core" }
rsiot-modbus-client = { version = "0.0.40", path = "./rsiot-modbus-client" }
rsiot-plc = { version = "0.0.40", path = "./rsiot-plc" }
rsiot-redis-client = { version = "0.0.40", path = "./rsiot-redis-client" }
rsiot-timescaledb-storing = { version = "0.0.40", path = "./rsiot-timescaledb-storing" }
rsiot-websocket-client = { version = "0.0.40", path = "./rsiot-websocket-client" }
rsiot-websocket-client-wasm = { version = "0.0.40", path = "./rsiot-websocket-client-wasm" }
rsiot-websocket-server = { version = "0.0.40", path = "./rsiot-websocket-server" }
