[workspace]
members = [
    "./rsiot",
    "./rsiot-component-core",
    "./rsiot-components-config",
    "./rsiot-env-vars",
    "./rsiot-extra-components",
    "./rsiot-http-client",
    "./rsiot-http-server",
    "./rsiot-messages-core",
    "./rsiot-modbus-client",
    "./rsiot-redis-publisher",
    "./rsiot-redis-subscriber",
    "./rsiot-timescaledb-storing",
    "./rsiot-websocket-server",
    "./rsiot-websocket-client",
]
resolver = "2"


[workspace.package]
categories = ["api-bindings", "gui", "network-programming"]
edition = "2021"
keywords = ["iot"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Konstantin-Dudersky/rsiot"
rust-version = "1.74.0"


[workspace.dependencies]
axum = { version = "0.7.1" }
axum-test = { version = "13.4.1" }
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4", features = ["derive"] }
dotenvy = { version = "0.15" }
envy = { version = "0.4" }
http = { version = "1.0.0" }
futures = { version = "0.3.29" }
futures-util = { version = "0.3.29" }
redis = { version = "0.23.3", features = ["tokio-comp"] }
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = { version = "1.0.108" }
sqlx = { version = "0.7.3", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
] }
tokio = { version = "1.34.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-modbus = { version = "0.9.0", default-features = false, features = [
    "tcp",
] }
tokio-tungstenite = { version = "0.20.1" }
tokio-util = { version = "0.7.10" }
toml = { version = "0.8" }
tower-http = { version = "0.5.0", features = ["cors", "trace"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
url = { version = "2.5.0" }

# документация
document-features = { version = "0.2.7" }

# для макросов
proc-macro2 = "1.0"
proc-macro-error = "1.0"
quote = "1.0"
syn = "2.0"


rsiot-component-core = { version = "0.0.15", path = "./rsiot-component-core" }
rsiot-components-config = { version = "0.0.15", path = "./rsiot-components-config" }
rsiot-env-vars = { version = "0.0.15", path = "./rsiot-env-vars" }
rsiot-extra-components = { version = "0.0.15", path = "./rsiot-extra-components" }
rsiot-http-client = { version = "0.0.15", path = "./rsiot-http-client" }
rsiot-http-server = { version = "0.0.15", path = "./rsiot-http-server" }
rsiot-messages-core = { version = "0.0.15", path = "./rsiot-messages-core" }
rsiot-modbus-client = { version = "0.0.15", path = "./rsiot-modbus-client" }
rsiot-redis-publisher = { version = "0.0.15", path = "./rsiot-redis-publisher" }
rsiot-redis-subscriber = { version = "0.0.15", path = "./rsiot-redis-subscriber" }
rsiot-timescaledb-storing = { version = "0.0.15", path = "./rsiot-timescaledb-storing" }
rsiot-websocket-client = { version = "0.0.15", path = "./rsiot-websocket-client" }
rsiot-websocket-server = { version = "0.0.15", path = "./rsiot-websocket-server" }
