[workspace]
members = [
    "./rsiot",
    "./rsiot-component-core",
    "./rsiot-components-config",
    "./rsiot-env-vars",
    "./rsiot-extra-components",
    "./rsiot-influxdb",
    "./rsiot-http-client",
    "./rsiot-http-client-wasm",
    "./rsiot-http-server",
    "./rsiot-leptos",
    "./rsiot-logging",
    "./rsiot-macros",
    "./rsiot-messages-core",
    "./rsiot-plc",
    "./rsiot-redis-client",
    "./rsiot-surrealdb",
    "./rsiot-timescaledb-storing",
    "./rsiot-websocket-client",
    "./rsiot-websocket-client-wasm",
]
exclude = ["./rsiot-esp"]
resolver = "2"


[workspace.package]
categories = ["api-bindings", "gui", "network-programming"]
edition = "2021"
keywords = ["iot", "scada"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Konstantin-Dudersky/rsiot"
rust-version = "1.75.0"


[workspace.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

# async
async-trait = { version = "0.1.77" }
futures = { version = "0.3.30" }
tokio = { version = "^1.36.0", features = ["macros", "sync", "rt", "time"] }
tokio-util = { version = "0.7.10" }

# CLI
clap = { version = "^4.4.18", features = ["derive"] }

# datatypes
chrono = { version = "0.4.33", features = ["serde"] }
http = { version = "1.0.0" }
# TODO - заменить на palette?
rgb = { version = "0.8.37", features = ["serde"] }
palette = { version = "0.7.4", features = ["named"] }
url = { version = "2.5.0" }
uuid = { version = "1.7.0", features = ["serde", "v4"] }

# documentation
document-features = { version = "0.2.8" }

# database
redis = { version = "0.24.0", features = ["tokio-comp"] }


surrealdb = { version = "1.2.0" }

# env vars
dotenvy = { version = "0.15.7" }
envy = { version = "0.4.2" }

# errors
anyhow = { version = "1.0.79" }
thiserror = { version = "1.0.56" }

# HTTP-client
reqwest = { version = "0.11.23", features = ["json"] }

# HTTP-server
axum = { version = "0.7.4" }
axum-test = { version = "14.2.2" }
tower-http = { version = "0.5.1", features = ["cors", "trace"] }


# logging
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }
tracing-loki = { version = "0.2.4" }
tracing-web = { version = "0.1.3" }

# macro
proc-macro2 = { version = "1.0.78" }
proc-macro-error = { version = "1.0.4" }
quote = { version = "1.0.35" }
syn = { version = "2.0.48" }

# Modbus
tokio-modbus = { version = "0.11.0", default-features = false, features = [
    "tcp",
] }

# serialization / deserialization
serde = { version = "1.0.196", features = ["derive"] }
serde_json = { version = "1.0.113" }
toml = { version = "0.8.9" }

# WASM
gloo = { version = "0.11.0", features = [
    "net",
    "futures",
    "storage",
    "timers",
    "utils",
] }
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
leptos = { version = "0.6.5", features = ["csr"] }
leptos_router = { version = "0.6.5", features = ["csr"] }
web-sys = { version = "0.3.68", features = ["Location", "Window"] }

# Websocket
tokio-tungstenite = { version = "0.21.0" }

# [target.'cfg(any(target_arch = "x86_64", target_arch = "aarch64"))'.workspace.dependencies]
sqlx = { version = "0.7.3", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
] }


# workspace packages
rsiot-component-core = { version = "0.0.71", path = "./rsiot-component-core" }
rsiot-components-config = { version = "0.0.70", path = "./rsiot-components-config" }
rsiot-env-vars = { version = "0.0.62", path = "./rsiot-env-vars" }
rsiot-extra-components = { version = "0.0.71", path = "./rsiot-extra-components" }
rsiot-http-client = { version = "0.0.71", path = "./rsiot-http-client" }
rsiot-http-client-wasm = { version = "0.0.71", path = "./rsiot-http-client-wasm" }
rsiot-http-server = { version = "0.0.71", path = "./rsiot-http-server" }
rsiot-influxdb = { version = "0.0.71", path = "./rsiot-influxdb" }
rsiot-leptos = { version = "0.0.71", path = "./rsiot-leptos" }
rsiot-logging = { version = "0.0.62", path = "./rsiot-logging" }
rsiot-macros = { version = "0.0.64", path = "./rsiot-macros" }
rsiot-messages-core = { version = "0.0.70", path = "./rsiot-messages-core" }
rsiot-plc = { version = "0.0.71", path = "./rsiot-plc" }
rsiot-surrealdb = { version = "0.0.71", path = "./rsiot-surrealdb" }
rsiot-redis-client = { version = "0.0.71", path = "./rsiot-redis-client" }
rsiot-timescaledb-storing = { version = "0.0.71", path = "./rsiot-timescaledb-storing" }
rsiot-websocket-client = { version = "0.0.71", path = "./rsiot-websocket-client" }
rsiot-websocket-client-wasm = { version = "0.0.71", path = "./rsiot-websocket-client-wasm" }
