[workspace]
members = [
    "./rsiot-modbus-client",
    "./rsiot-modbus-client-config",
    "./rsiot-messages-core",
    "./libraries/async-task-utils",
]
resolver = "2"


[workspace.dependencies]
tokio-modbus = { version = "0.9", default-features = false, features = ["tcp"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
tracing = { version = "0.1" }
url = { version = "2.4" }

async-task-utils = { path = "./libraries/async-task-utils" }
rsiot-messages-core = { path = "./rsiot-messages-core" }
rsiot-modbus-client = { path = "./rsiot-modbus-client" }
rsiot-modbus-client-config = { path = "./rsiot-modbus-client-config" }

# rsiot-modbus-client = { version = "0.0" }
# rsiot-modbus-client-config = { version = "0.0" }
