[workspace]
members = [
    "./rsiot",
    "./rsiot-component-core",
    "./rsiot-extra-components",
    "./rsiot-http-client",
    "./rsiot-http-client-config",
    "./rsiot-http-server",
    "./rsiot-messages-core",
    "./rsiot-modbus-client",
    "./rsiot-modbus-client-config",
    "./rsiot-redis-publisher",
    "./rsiot-redis-subscriber",
    "./rsiot-timescaledb-storing",
    "./rsiot-websocket-server",
    "./rsiot-websocket-client",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.70.0"


[workspace.dependencies]
axum = { version = "0.6" }
axum-test = { version = "13.1" }
chrono = { version = "0.4", features = ["serde"] }
http = { version = "1.0" }
hyper = { version = "0.14" }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
redis = { version = "0.23", features = ["tokio-comp"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sqlx = { version = "0.7", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
] }
tokio = { version = "1", features = ["full"] }
tokio-modbus = { version = "0.9", default-features = false, features = ["tcp"] }
tokio-tungstenite = { version = "0.20" }
tokio-util = { version = "0.7" }
tower-http = { version = "0.4", features = ["cors", "trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
url = { version = "2.4" }

# документация
document-features = { version = "0.2" }

rsiot-extra-components = { version = "0.0.6", path = "./rsiot-extra-components" }
rsiot-component-core = { version = "0.0.6", path = "./rsiot-component-core" }
rsiot-http-client = { version = "0.0.6", path = "./rsiot-http-client" }
rsiot-http-client-config = { version = "0.0.6", path = "./rsiot-http-client-config" }
rsiot-http-server = { version = "0.0.6", path = "./rsiot-http-server" }
rsiot-messages-core = { version = "0.0.6", path = "./rsiot-messages-core" }
rsiot-modbus-client = { version = "0.0.6", path = "./rsiot-modbus-client" }
rsiot-modbus-client-config = { version = "0.0.6", path = "./rsiot-modbus-client-config" }
rsiot-redis-publisher = { version = "0.0.6", path = "./rsiot-redis-publisher" }
rsiot-redis-subscriber = { version = "0.0.6", path = "./rsiot-redis-subscriber" }
rsiot-timescaledb-storing = { version = "0.0.6", path = "./rsiot-timescaledb-storing" }
rsiot-websocket-client = { version = "0.0.6", path = "./rsiot-websocket-client" }
rsiot-websocket-server = { version = "0.0.6", path = "./rsiot-websocket-server" }
