[workspace]
members = [
    "./rsiot-channel-utils",
    "./rsiot-http-client",
    "./rsiot-http-client-config",
    "./rsiot-http-server",
    "./rsiot-messages-core",
    "./rsiot-modbus-client",
    "./rsiot-modbus-client-config",
    "./rsiot-redis-publisher",
    "./rsiot-redis-subscriber",
    "./rsiot-timescaledb-storing",
    "./rsiot-websocket-server",
    "./libraries/async-task-utils",
]
resolver = "2"


[workspace.dependencies]
axum = { version = "0.6" }
axum-test = { version = "13.1" }
chrono = { version = "0.4", features = ["serde"] }
hyper = { version = "0.14" }
futures-util = { version = "0.3" }
redis = { version = "0.23", features = ["tokio-comp"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
sqlx = { version = "0.7", features = [
    "chrono",
    "macros",
    "postgres",
    "runtime-tokio",
] }
tokio = { version = "1", features = ["full"] }
tokio-modbus = { version = "0.9", default-features = false, features = ["tcp"] }
tokio-tungstenite = { version = "0.20" }
tokio-util = { version = "0.7" }
tower-http = { version = "0.4", features = ["cors", "trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
url = { version = "2.4" }


async-task-utils = { path = "./libraries/async-task-utils" }
rsiot-channel-utils = { path = "./rsiot-channel-utils" }
rsiot-messages-core = { path = "./rsiot-messages-core" }
rsiot-modbus-client = { path = "./rsiot-modbus-client" }
rsiot-modbus-client-config = { path = "./rsiot-modbus-client-config" }
rsiot-redis-publisher = { path = "./rsiot-redis-publisher" }
rsiot-redis-subscriber = { path = "./rsiot-redis-subscriber" }
rsiot-timescaledb-storing = { path = "./rsiot-timescaledb-storing" }
rsiot-websocket-server = { path = "./rsiot-websocket-server" }

# rsiot-modbus-client = { version = "0.0" }
# rsiot-modbus-client-config = { version = "0.0" }
