version: "3.8"
name: rsiot-dev

services:
  timescaledb:
    container_name: timescaledb
    hostname: timescaledb
    image: timescale/timescaledb:2.12.2-pg15
    command: postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./rsiot-config-files/timescaledb/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./rsiot-config-files/timescaledb/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./rsiot-config-files/timescaledb/init.sql:/docker-entrypoint-initdb.d/init.sql

  # для тестирования http-client
  httpbin:
    container_name: httpbin
    hostname: httpbin
    image: kennethreitz/httpbin
    ports:
      - "80:80"

  # для тестирования websocket
  websocket-client-testing:
    container_name: websocket-client-testing
    hostname: websocket-client-testing
    image: crossbario/autobahn-testsuite
    ports:
      - "9001:9001"
    command: wstest -m broadcastserver -w ws://localhost:9001

  # для тестирования modbus-client
  modbus-server:
    container_name: modbus-server
    hostname: modbus-server
    image: oitc/modbus-server
    ports:
      - "5020:5020"
    volumes:
      - ./rsiot-modbus-client/modbus_server.json:/app/modbus_server.json

  # redis
  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379" # порт Redis
      - "8002:8001" # порт UI
    volumes:
      - redis_data:/data
      - ./services/redis/redis.conf:/redis-stack.conf

volumes:
  redis_data:
    name: redis_data
