[package]
name = "test_slint_android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "*"
rsiot = { path = "../../../rsiot", features = [
    "executor",
    "cmp_slint",
    "cmp_http_client",
] }
tokio = { version = "*", features = ["rt-multi-thread", "macros", "time"] }
tracing = "*"
tracing-subscriber = "*"
openssl = { version = "*", features = ["vendored"] }
serde_json = { version = "*" }
url = { version = "*" }
serde = { version = "*", features = ["derive"] }

slint = { version = "1.5", features = ["backend-android-activity-05"] }

[build-dependencies]
slint-build = "1.5.0"


[package.metadata.android]
# Specifies the array of targets to build for.
build_targets = [
    # "armv7-linux-androideabi",
    "aarch64-linux-android",
    # "i686-linux-android",
    # "x86_64-linux-android",
]


[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.uses_permission]]
name = "android.permission.ACCESS_NETWORK_STATE"

[package.metadata.android.sdk]
target_sdk_version = 34
