import { Button, LineEdit } from "std-widgets.slint";

export global GlobalData {
    in property <string> primary: "1235";
    in property <string> secondary: "456";

    pure callback relay_control(bool);
}

global Style {
    in property <length> font-size: 20pt;
    in property <color> TEXT_COLOR: white;
}

export component MainWindow inherits Window {
    width: 400px;
    height: 800px;
    Text {
        text: GlobalData.primary;
    }

    Button {
        width: 160px;
        x: 13px;
        y: 273px;

        text: "Включить";

        clicked => {
            GlobalData.relay_control(true)
        }
    }

    Button {
        width: 160px;
        x: 203px;
        y: 272px;

        text: "Отключить";

        clicked => {
            GlobalData.relay_control(false)
        }
    }

    LineEdit {
        x: 114px;
        y: 600px;
        placeholder-text: "Enter text here";
    }
}
