[package]
name = "rsiot-modbus-client-config"
version = "0.0.6"
description = "Конфигурация для Modbus клиента"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
url = { workspace = true }
