[package]
name = "modbus-client"
version = "0.0.1"
edition = "2021"


[dependencies]
tokio = { workspace = true }
tokio-modbus = { workspace = true }

messages-lib = { workspace = true }
modbus-client-config = { workspace = true }
