[package]
name = "rsiot-websocket-client"
version = "0.0.0"
edition = "2021"


[dependencies]
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-component-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }

rsiot-channel-utils = { workspace = true }
