# d2 fmt diagram.d2; d2 diagram.d2 - | oxvg optimise | save -f -r diagram.svg

...@../../../../doc/images/component_structure/style

MsgBusIn: MsgBus {
  shape: oval
}

InjectPeriodic
InjectPeriodic -> MsgBusOut

MsgBusOut: MsgBus {
  shape: oval
}
