[package]
name = "rsiot-redis-subscriber"
version = "0.0.1"
edition = "2021"


[dependencies]
futures-util = { workspace = true }
redis = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
