[package]
name = "hmi-ui"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
any_spawner = "*"
serde = { version = "1", features = ["derive"] }
strum = { version = "*", features = ["derive"] }
rsiot = { path = "../../../", features = [
    "cmp_leptos",
    "cmp_websocket_client_wasm",
    "log_webconsole",
    "single-thread",
    "serde_json",
] }
tokio = { version = "1.47.1", features = ["rt"] }
tracing = "*"
gloo = { version = "0.11.0", features = [
    "dialogs",
    "futures",
    "net",
    "storage",
    "timers",
    "utils",
] }

leptos = { version = "0.8.10", features = ["csr"] }
