[package]
name = "rsiot-http-client-config"
version = "0.0.5"
description = "Конфигурация HTTP-клиента"
license.workspace = true
edition.workspace = true
rust-version.workspace = true


[dependencies]
http = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
