services:
  service_grafana:
    container_name: service_grafana
    hostname: service_grafana
    image: grafana/grafana:12.0.2 # https://hub.docker.com/r/grafana/grafana/tags
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
        # настройки источника - TimescaleDB
      - TIMESCALEDB_HOST=timescaledb
      - TIMESCALEDB_PORT=5432
      - TIMESCALEDB_DB_DATA=db_data
        # настройки источника - логгер loki
      - LOKI_HOST=loki
      - LOKI_PORT=3100
        # настройки источника - InfluxDB 3
      - INFLUXDB_HOST=uscada-influxdb
      - INFLUXDB_PORT=8181
      - INFLUXDB_dbName=mydb
    networks:
      - network_internal
    ports:
      - "3000:3000"
    profiles:
      - dev
      - target
    volumes:
      - ./config_services/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./config_services/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: "root:root"

networks:
  network_internal:
