# d2 fmt diagram.d2; d2 diagram.d2 - | oxvg optimise | save -f -r diagram.svg

...@../../../../doc/images/component_structure/style

ch_rx_msgbus_to_device: {
  class: msgbus
}
ch_rx_msgbus_to_device -> InputRequest: "1"

InputRequest: |md
  **InputRequest**

  Mutex:
  - Buffer
  - DeviceState
| {
  shape: rectangle
}
InputRequest -> BufferToRequests: "ch_need_request"

BufferPeriodic
BufferPeriodic -> BufferToRequests: "ch_need_request"

BufferToRequests
BufferToRequests -> Request: "ch_request"

InitRequest
InitRequest -> Request: "ch_request"

PeriodicRequest
PeriodicRequest -> Request: "ch_request"

Request
Request -> ch_tx_device_to_fieldbus: "2"

ch_tx_device_to_fieldbus: {
  class: msgbus
}

ch_rx_fieldbus_to_device: {
  class: msgbus
}

ch_rx_fieldbus_to_device -> Response: "3"

Response
Response -> FilterIdenticalData: "ch_output_to_filter"
Response -> BufferToRequests: "ch_need_request"
Response -> ch_tx_device_to_diag

FilterIdenticalData
FilterIdenticalData -> ch_tx_device_to_msgbus: "4"

ch_tx_device_to_diag: {
  class: msgbus
}

ch_tx_device_to_msgbus: {
  class: msgbus
}
