# d2 fmt diagram.d2; d2 diagram.d2 - | oxvg optimise | save -f -r diagram.svg

...@../../../../doc/images/component_structure/style

MsgBusIn: MsgBus {
  class: msgbus
}
MsgBusIn -> InputRequest: "1"

InputRequest
InputRequest -> BufferToRequests: "ch_need_request"

BufferPeriodic
BufferPeriodic -> BufferToRequests: "ch_need_request"

BufferToRequests
BufferToRequests -> Request: "ch_request"

InitRequest
InitRequest -> Request: "ch_request"

PeriodicRequest
PeriodicRequest -> Request: "ch_request"

Request
Request -> FieldbusProcess: "2"

FieldbusProcess: {
  style.stroke-dash: 5
}
FieldbusProcess -> Response: "3"

Response
Response -> FilterIdenticalData: "ch_output_to_filter"
Response -> BufferToRequests: "ch_need_request"

FilterIdenticalData
FilterIdenticalData -> MsgBusOut: "4"

MsgBusOut: MsgBus {
  class: msgbus
}
