[package]
name = "rsiot-redis-publisher"
version = "0.0.2"
edition = "2021"
description = "Публикация сообщений в Redis"
license = "MIT"


[dependencies]
redis = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-channel-utils = { workspace = true }
rsiot-component-core = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
serde = { workspace = true }
