[target.aarch64-linux-android]
linker = "/home/konstantin/Android/Sdk/ndk/29.0.14033849/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
rustflags = [
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C",
    "target-feature=+crt-static",
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    "-C",
    "target-feature=+crt-static",
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
    "--cfg",
    "espidf_time64",
    "--cfg",
    "mio_unsupported_force_poll_poll", # https://github.com/tokio-rs/tokio/issues/5866
    # для tokio-console
    "--cfg",
    "tokio_unstable",
    # "-C",
    # "force-frame-pointers",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[target.wasm32-unknown-unknown]
rustflags = [
    # для tokio-console
    "--cfg",
    "tokio_unstable",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c3"
# install all libraries globally, in folder ~/.espressif
ESP_IDF_TOOLS_INSTALL_DIR = "global"
# check current version on https://docs.espressif.com/projects/esp-idf/en/latest/esp32/index.html
ESP_IDF_VERSION = "v5.3.2"

ANDROID_HOME = "/home/konstantin/Android/Sdk"
JAVA_HOME = "/snap/android-studio/current/jbr/"
ANDROID_NDK_HOME="/home/konstantin/Android/Sdk/ndk/29.0.14033849"
ANDROID_NDK_ROOT="/home/konstantin/Android/Sdk/ndk/29.0.14033849"
CC_aarch64-linux-android = "/home/konstantin/Android/Sdk/ndk/29.0.14033849/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
CCX_aarch64-linux-android = "/home/konstantin/Android/Sdk/ndk/29.0.14033849/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang++"
AR_aarch64-linux-android = "/home/konstantin/Android/Sdk/ndk/29.0.14033849/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
RANLIB_aarch64-linux-android = "/home/konstantin/Android/Sdk/ndk/29.0.14033849/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib"
