[package]
name = "rsiot-modbus-client"
version = "0.0.6"
description = "Опрос устройств Modbus, используя библиотеку tokio-modbus"
license.workspace = true
edition.workspace = true
rust-version.workspace = true


[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
tokio-modbus = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-modbus-client-config = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
