[package]
name = "rsiot-modbus-client"
version = "0.0.3"
edition = "2021"
description = "Опрос устройств Modbus, используя библиотеку tokio-modbus"
license = "MIT"


[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
tokio-modbus = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-modbus-client-config = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
