[package]
name = "rsiot-modbus-client"
version = "0.0.1"
edition = "2021"
description = "Опрос устройств Modbus, используя библиотеку tokio-modbus"
license = "MIT"


[dependencies]
tokio = { workspace = true }
tokio-modbus = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-modbus-client-config = { workspace = true }
