[package]
name = "rsiot-http-server"
version = "0.0.3"
edition = "2021"
description = "HTTP-сервер"
license = "MIT"

[dependencies]
axum = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tower-http = { workspace = true }
url = { workspace = true }

rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
