[package]
name = "rsiot-http-server"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tower-http = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-channel-utils = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
