[package]
name = "rsiot-http-server"
version = "0.0.4"
description = "HTTP-сервер"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
axum = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tower-http = { workspace = true }
url = { workspace = true }

rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }


[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
