services:
  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379" # порт Redis
      - "${REDIS_PORT_UI}:8001" # порт UI
    volumes:
      - redis_data:/data # для сохранения данных
      - ./services/redis/redis.conf:/redis-stack.conf # путь к файлу конфигурации

volumes:
  redis_data:
    name: redis_data
