[package]
# categories.workspace = true
description = "Чтение входов GPIO микроконтроллера ESP."
edition = "2021"
# keywords.workspace = true
# license.workspace = true
name = "rsiot-esp"
readme = "README.md"
# repository.workspace = true
# rust-version.workspace = true
version = "0.0.0"

[profile.release]
opt-level = "s"


[profile.dev]
debug = true
opt-level = "z"


[dependencies]
tokio = { version = "*" }
esp-idf-svc = { version = "0.47.3", features = ["std"] }
embedded-svc = { version = "*" }
tracing = { version = "*" }

rsiot-component-core = { version = "0.0.27", path = "../rsiot-component-core" }
rsiot-extra-components = { version = "0.0.27", path = "../rsiot-extra-components" }
rsiot-messages-core = { version = "0.0.26", path = "../rsiot-messages-core" }

[build-dependencies]
embuild = "0.31.3"
