[package]
name = "modbus-test"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-modbus = { workspace = true }

messages = { workspace = true }
modbus-config = { workspace = true }
