[package]
name = "modbus-test"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { workspace = true }
url = { workspace = true }

messages = { workspace = true }
modbus-client = { workspace = true }
modbus-client-config = { workspace = true }
