[package]
categories.workspace = true
description = "Метакрейт, импортирующий все другие крейты через флаги feature"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsiot"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.0.71"


[dependencies]
anyhow = { version = "1.0.80" }
async-trait = { version = "0.1.77" }
serde = { version = "1.0.197", features = ["derive"] }
thiserror = { version = "1.0.57" }
tracing = { version = "0.1.40", features = ["log"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "chrono"] }

# cmp_auth
jwt = { version = "0.16.0", optional = true }
hmac = { version = "0.12.1", optional = true }
sha2 = { version = "0.10.8", optional = true }

# cmp_modbus_client
tokio-modbus = { version = "0.11.0", default-features = false, features = [
    "tcp",
], optional = true }

# cmp_webstorage
gloo = { version = "0.11.0", features = [
    "futures",
    "net",
    "storage",
    "timers",
    "utils",
], optional = true }

# cmp_websocket_server
tokio-util = { version = "0.7.10", optional = true }
tokio-tungstenite = { version = "0.21.0", optional = true }
futures = { version = "0.3.30", optional = true }

document-features = { workspace = true }

tokio = { workspace = true, optional = true }
chrono = { workspace = true }
url = { workspace = true }


rsiot-component-core = { workspace = true, optional = true }
rsiot-env-vars = { workspace = true, optional = true }
rsiot-extra-components = { workspace = true, optional = true }
rsiot-http-client = { workspace = true, optional = true }
rsiot-http-client-wasm = { workspace = true, optional = true }
rsiot-http-server = { workspace = true, optional = true }
rsiot-influxdb = { workspace = true, optional = true }
rsiot-leptos = { workspace = true, optional = true }
rsiot-logging = { workspace = true }
rsiot-messages-core = { workspace = true, features = ["serde-json"] }
rsiot-plc = { workspace = true, optional = true }
rsiot-redis-client = { workspace = true, optional = true }
rsiot-surrealdb = { workspace = true, optional = true }
rsiot-websocket-client = { workspace = true, optional = true }
rsiot-websocket-client-wasm = { workspace = true, optional = true }
rsiot-timescaledb-storing = { workspace = true, optional = true }


[target.'cfg(any(target_arch = "x86_64", target_arch = "aarch64"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }


[features]
## Базовые компоненты
components = [
    "dep:tokio",
    "dep:rsiot-extra-components",
    "dep:rsiot-component-core",
]

## Компонент аутентификации
cmp_auth = ["components", "dep:jwt", "dep:hmac", "dep:sha2"]

## Конфигурирование через переменные
env-vars = ["dep:rsiot-env-vars"]

## Компонент http-клиент
http-client = ["components", "dep:rsiot-http-client"]

## Компонент http-клиент для платформы WASM
http-client-wasm = ["components", "dep:rsiot-http-client-wasm"]

## Компонент http-сервер
http-server = ["components", "dep:rsiot-http-server"]

## Компонент сохранения в БД InfluxDB
influxdb = ["components", "dep:rsiot-influxdb"]

## Компонент для создания интерфейсов на базе Leptos
leptos = ["components", "dep:rsiot-leptos"]

## Компонент Modbus клиент
cmp_modbus_client = ["components", "dep:tokio-modbus"]

# Компонент ПЛК
plc = ["components", "dep:rsiot-plc"]

## Компонент клиента Redis
redis-client = ["components", "dep:rsiot-redis-client"]

## Компонент доступа к БД SurrealDB
surrealdb = ["components", "dep:rsiot-surrealdb"]

## Компонент сохранения в БД TimescaleDB
timescaledb-storing = ["components", "dep:rsiot-timescaledb-storing"]

## Компонент websocket клиента
websocket-client = ["components", "dep:rsiot-websocket-client"]

## Компонент websocket клиента
websocket-client-wasm = ["components", "dep:rsiot-websocket-client-wasm"]

## Компонент websocket сервера
cmp_websocket_server = [
    "components",
    "dep:futures",
    "dep:tokio-tungstenite",
    "dep:tokio-util",
]

## Хранение и загрузка сообщений используя Web Storage API браузера
cmp_webstorage = ["components", "dep:gloo"]

## Работа в одном потоке, в LocalSet
single-thread = [
    "rsiot-component-core?/single-thread",
    "rsiot-extra-components?/single-thread",
    "rsiot-http-client?/single-thread",
    "rsiot-http-client-wasm?/single-thread",
    "rsiot-http-server?/single-thread",
    "rsiot-influxdb?/single-thread",
    "rsiot-leptos?/single-thread",
    "rsiot-plc?/single-thread",
    "rsiot-redis-client?/single-thread",
    "rsiot-surrealdb?/single-thread",
    "rsiot-timescaledb-storing?/single-thread",
    "rsiot-websocket-client?/single-thread",
    "rsiot-websocket-client-wasm?/single-thread",
]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
