[package]
categories.workspace = true
description = "Метакрейт, импортирующий все другие крейты через флаги feature"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsiot"
readme = "README.md"
rust-version.workspace = true
version = "0.0.14"

[dependencies]
document-features = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-extra-components = { workspace = true }
rsiot-http-client = { workspace = true }
rsiot-http-server = { workspace = true }
rsiot-messages-core = { workspace = true }
rsiot-modbus-client = { workspace = true }
rsiot-redis-publisher = { workspace = true }
rsiot-redis-subscriber = { workspace = true }
rsiot-websocket-client = { workspace = true }
rsiot-websocket-server = { workspace = true }
rsiot-timescaledb-storing = { workspace = true }

[dev-dependencies]
# tokio = { workspace = true }
# serde = { workspace = true }

[features]
## Базовые компоненты
components = []
## Компонент http-клиент
http-client = ["components"]
## Компонент http-сервер
http-server = ["components"]
## Компонент Modbus клиент
modbus-client = ["components"]
## Компонент публикации сообщений в Redis
redis-publisher = ["components"]
## Компонент подписики на сообщения из Redis
redis-subscriber = ["components"]
## Компонент сохранения в БД TimescaleDB
timescaledb-storing = ["components"]
## Компонент websocket клиента
websocket-client = ["components"]
## Компонент websocket сервера
websocket-server = ["components"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
