[package]
name = "rsiot-websocket-server"
version = "0.0.2"
edition = "2021"
description = "Websocket-сервер"
license = "MIT"


[dependencies]
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-messages-core = { workspace = true }
rsiot-channel-utils = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
