[package]
name = "rsiot-websocket-server"
version = "0.0.4"
description = "Websocket-сервер"
license.workspace = true
edition.workspace = true
rust-version.workspace = true


[dependencies]
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
