[package]
categories.workspace = true
description = "Компонент для исполнения логики наподобие PLC"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "rsiot-plc"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.0.29"


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }


[dev-dependencies]
tracing-subscriber = { workspace = true }
