[package]
name = "rsiot-plc"
version = "0.0.26"
edition = "2021"


[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-extra-components = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
