[package]
name = "rsiot-http-client"
version = "0.0.8"
description = "HTTP-клиент"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-extra-components = { workspace = true }
rsiot-http-client-config = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true }
