[package]
name = "rsiot-http-client"
version = "0.0.2"
edition = "2021"
description = "HTTP-клиент"
license = "MIT"

[dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

rsiot-http-client-config = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
