[package]
name = "test_slint"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
futures = "*"
rsiot = { path = "../", features = [
    "cmp_raspberrypi",
    "cmp_slint",
    "cmp_system_info",
] }
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["rt-multi-thread", "macros", "time"] }
tracing = "*"
tracing-subscriber = "*"

slint = { version = "*", features = [
    "backend-linuxkms-noseat",
    "renderer-skia",
] }

[build-dependencies]
slint-build = "*"
