[package]
name = "test_slint"
version = "0.1.0"
edition = "2021"
build = "build.rs"


[dependencies]
futures = "*"
rsiot = { path = "../rsiot", features = [
    "executor",
    # "single-thread",
    "cmp_slint",
] }
tokio = { version = "*", features = ["rt-multi-thread", "macros", "time"] }
tracing = "*"
tracing-subscriber = "*"

# slint = "*"
slint = { version = "*", features = [
    "backend-linuxkms-noseat",
    "renderer-skia",
] }

[build-dependencies]
slint-build = "1.5.0"
