import { Button, LineEdit } from "std-widgets.slint";
import { VirtualKeyboardHandler, VirtualKeyboard, KeyModel } from "./ui/virtual_keyboard.slint";

export { VirtualKeyboardHandler, KeyModel }

export global GlobalData {
    in property <string> os_version: "OS";
    in property <string> host_name: "hostname";

    in property <string> eth0_mac: "nw_0_mac";
    in property <string> wlan0_mac: "nw_0_mac";

    in property <string> cpu_load: "100.0% 100.0% 100.0% 100.0%";

    in property <string> cpu_temp: "100.0 ℃";

    in property <string> memory: "1000 MB / 4000 MB";
    in property <string> swap: "1000 MB / 4000 MB";

    in property <string> dev_sda_1: "1000 GB / 4000 GB";
    in property <string> dev_sda_2: "1000 GB / 4000 GB";

    pure callback button(int);
}

global Style {
    in property <length> font-size: 16pt;
    // in property <color> TEXT_COLOR: black;
    in property <length> font-size-2: 26pt;
}

export component MainWindow inherits Window {
    width: 800px;
    height: 480px;
    // background: white;

    Image {
        x: 0px;
        y: 416px;
        width: 64px;
        source: @image-url("./assets/logo_color.svg");
    }

    Button {
        x: 400px;
        y: 200px;
        text: "Button 1";
    }

    LineEdit {
        x: 400px;
        y: 280px;
        width: 200px;
        font-size: Style.font-size-2;
        placeholder-text: "Text 1";
    }

    LineEdit {
        x: 400px;
        y: 360px;
        width: 200px;
        font-size: Style.font-size-2;
        placeholder-text: "Text 2";
    }

    // host_name -----------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 8px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "Host:";
    }

    Text {
        x: 80px;
        y: 8px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.host_name;
    }

    // os_version ----------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 40px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "OS:";
    }

    Text {
        x: 80px;
        y: 40px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.os_version;
    }

    // Networks ------------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 72px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "Networks:";
    }

    Text {
        x: 40px;
        y: 104px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "eth0:";
    }

    Text {
        x: 80px;
        y: 136px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.eth0_mac;
    }

    Text {
        x: 40px;
        y: 168px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "wlan0:";
    }

    Text {
        x: 80px;
        y: 200px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.wlan0_mac;
    }

    // CPU -----------------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 232px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "CPU:";
    }

    Text {
        x: 80px;
        y: 232px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.cpu_load;
    }

    // Temperature ---------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 264px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "Temp:";
    }

    Text {
        x: 80px;
        y: 264px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.cpu_temp;
    }

    // Memory --------------------------------------------------------------------------------------
    Text {
        x: 8px;
        y: 296px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "RAM:";
    }

    Text {
        x: 80px;
        y: 296px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.memory;
    }

    Text {
        x: 8px;
        y: 328px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "Swap:";
    }

    Text {
        x: 80px;
        y: 328px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.swap;
    }

    // Disk ----------------------------------------------------------------------------------------
    Text {
        x: 400px;
        y: 8px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "Disks:";
    }

    Text {
        x: 440px;
        y: 40px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "/dev/sda1:";
    }

    Text {
        x: 560px;
        y: 40px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.dev_sda_1;
    }

    Text {
        x: 440px;
        y: 72px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: "/dev/sda2:";
    }

    Text {
        x: 560px;
        y: 72px;
        font-size: Style.font-size;
        // color: Style.TEXT_COLOR;
        text: GlobalData.dev_sda_2;
    }

    // VirtualKeyboard {
    //     // visible: TextInputInterface.text-input-focused;
    //     y: 0px;
    //     visible: true;
    // }
}
