[package]
name = "rsiot-extra-components"
version = "0.0.3"
edition = "2021"
description = "Дополнительные компоненты"
license = "MIT"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }

rsiot-component-core = { workspace = true }
rsiot-messages-core = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
tracing-subscriber = { workspace = true }
