services:
  svc_tsdb:
    command: postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    container_name: svc_tsdb
    healthcheck:
      test: pg_isready -d db_data
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    hostname: svc_tsdb
    image: timescale/timescaledb:2.23.0-pg18 # https://hub.docker.com/r/timescale/timescaledb/tags
    networks:
      - network_internal
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    profiles:
      - dev
      - target
    user: postgres
    volumes:
      - ./svc_tsdb/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./svc_tsdb/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./svc_tsdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - timescaledb_volume:/var/lib/postgresql/data

networks:
  network_internal:

volumes:
  timescaledb_volume:
    name: timescaledb_volume
