listen_addresses = '*'
# max_locks_per_transaction = 10000
shared_preload_libraries = 'timescaledb'

# По умолчанию 100
max_connections = 200

# По умолчанию 1GB
max_wal_size = 2GB

# По умолчанию 16
timescaledb.max_background_workers = 100

# По умолчанию 8
max_worker_processes = 116

# По умолчанию 8
max_parallel_workers = 16

# Для запрещения вывода в консоль содержимого SQL о долгих транзакциях. По умолчанию ERROR
log_min_error_statement = PANIC
