[package]
name = "rsiot-messages-core"
version = "0.0.7"
description = "Базовые трейты для реализации типа сообщения"
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
