[package]
name = "rsiot-messages-core"
version = "0.0.4"
edition = "2021"
description = "Базовые трейты для реализации типа сообщения"
license = "MIT"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
